serviceProperties :
    serviceDataProperties:
        serviceGroupName : "cache"
        serviceName : "cache_standalone"
        ip : "172.18.0.51"
        port : 8111
        rootUrl : "/cache"
        redisInfoNeed : "true"
    zNodeInfoProperties:
        regZnodePath : "/regManageNode"
        regZnodeChildPath : "/regManageNode/regManageChildNode"
        depZnodePath : "/depManageNode"
        zookeeperHostport : "172.18.0.11:2191"

tomcatPort : 8111

logging.file : "/opt/cache/log/console.log"