serviceProperties :
    serviceDataProperties:
        serviceGroupName : "cache"
        serviceName : "cache_B"
        ip : "172.18.0.52"
        port : 8112
        rootUrl : "/cache"
        topicInfo : "{\"consumers\":{\"cacheTopic\":[\"cacheTopic_2\"]}}"
    zNodeInfoProperties:
        regZnodePath : "/regManageNode"
        regZnodeChildPath : "/regManageNode/regManageChildNode"
        depZnodePath : "/depManageNode"
        zookeeperHostport : "172.18.0.11:2191,172.18.0.12:2192,172.18.0.13:2193"
    kafkaProperties:
        consumers:
            cacheTopic_2:
                brokerList : "172.18.0.41:9101,172.18.0.42:9102,172.18.0.43:9103"
                consumerTopic : "cacheTopic_2"
                groupId : "cacheTopic"
                deserializerClass : "org.apache.kafka.common.serialization.StringDeserializer"

tomcatPort : 8112